### ISSUE TITLE
Problem creating TableCell contatining characters  not available in WinAnsiEncoding

### ISSUE THREAD

**Issue by funghi123** [dhorions/boxable#153]
Hello,

This code:

```
TableCell<PDPage> cell = row.createTableCell(columnWidths[i], "ąćęłńóśźż", document, page, 0, 0, 0);
```

throws an exception:

```
java.lang.IllegalArgumentException: U+0105 ('aogonek') is not available in this font Helvetica encoding: WinAnsiEncoding
	at org.apache.pdfbox.pdmodel.font.PDType1Font.encode(PDType1Font.java:425) [pdfbox-2.0.8.jar:2.0.8]
	at org.apache.pdfbox.pdmodel.font.PDFont.encode(PDFont.java:323) [pdfbox-2.0.8.jar:2.0.8]
	at org.apache.pdfbox.pdmodel.font.PDFont.getStringWidth(PDFont.java:352) [pdfbox-2.0.8.jar:2.0.8]
	at be.quodlibet.boxable.Paragraph.getLines(Paragraph.java:410) [boxable-1.5.jar:]
	at be.quodlibet.boxable.TableCell.fillTable(TableCell.java:131) [boxable-1.5.jar:]
	at be.quodlibet.boxable.TableCell.<init>(TableCell.java:70) [boxable-1.5.jar:]
	at be.quodlibet.boxable.TableCell.<init>(TableCell.java:53) [boxable-1.5.jar:]
	at be.quodlibet.boxable.Row.createTableCell(Row.java:110) [boxable-1.5.jar:]
```

The trouble is that there is no possibility to change font to Unicode one **before** creating a cell.
I can't also see any possibility to change text after creating a cell. I have found only this ugly workaround:

```
TableCell<PDPage> cell = row.createTableCell(columnWidths[i], "", document, page, 0, 0, 0);
cell.setFont(font);
cell.setFontSize(DEFAULT_FONT_SIZE);

try {
	Field tableData = cell.getClass().getDeclaredField("tableData");
	tableData.setAccessible(true);
	tableData.set(cell, "ąćęłńóśźż");
} catch (Exception e) {
	throw new RuntimeException(e);
}

cell.fillTable();
```

Regards

**Comment by funghi123** [comment]
OK, I have used FontUtils - however it is still not possible to change default font size used by `TableCell.createInnerTable`, so I am creating a new issue

**Comment by mailidpankaj** [comment]
Hi, 

I am using boxable with PDFBox to create tables in the PDF. I am creating a table cell with Russian, Turkish and Polish Characters, 
as below:

testsRow.createTableCell((15), "przeszedł", document, page, yStartNewPage, bottomMargin, 10);

but I get the below errors with above mentioned locales:

java.lang.IllegalArgumentException: U+0440 ('afii10082') is not available in this font Helvetica encoding: WinAnsiEncoding
java.lang.IllegalArgumentException: U+0142 ('lslash') is not available in this font Helvetica encoding: WinAnsiEncoding
java.lang.IllegalArgumentException: U+015B ('sacute') is not available in this font Helvetica encoding: WinAnsiEncoding

Please let me whether this problem is solved and how can I fix the problem?

Regards,
Pankaj

**Comment by Frulenzo** [comment]
Hi Pankaj,

Unfortunately you need to find the font which supports your "special" characters and that is well known boxable problem.

**Comment by mailidpankaj** [comment]
Hi Frulenzo,

Thanks for the reply. I have already found the font to support multiple European locales(NotoMono-Regular.ttf) or ArialUnicodeMS font to support CJK locales and I am able to write those special characters to the PDF using PDFBox libraries. It's just that when I try to write the same characters inside the cell, I get these errors.

So, the problem is not the font or writing to PDF now, only writing the characters to the table cell. Is there anything we can do ?

Regards,
Pankaj

**Comment by Frulenzo** [comment]
Did you used FontUtils addFont() Method?

`public static void addDefaultFonts(final PDFont font,final PDFont fontBold,final PDFont fontItalic,final PDFont fontBoldItalic) `
