### ISSUE TITLE
Adding an Image Using Boxable.

### ISSUE THREAD

**Issue by D40483497** [dhorions/boxable#18]
I was not able to find out if we can add an image to the PDF using the Boxable.

**Comment by Kravs** [comment]
Hello,
Boxable is based on PDFBox.
So you could try to use it directly:

http://stackoverflow.com/questions/8521290/cant-add-an-image-to-a-pdf-using-pdfbox

I'm not sure if that is the best approach but it worth trying.

**Comment by Frulenzo** [comment]
Just little heads up. PDJpeg class is deprecated in current version (Apache PDFBox 2.0.0 RC2) so maybe PDImageXObject is better way to go.

Something like 

```java
BufferedImage image = ...;
PDImageXObject imageXObject = LosslessFactory.createFromImage(document, image);
stream.drawImage(imageXObject, x, y - image.getHeight(), image.getWidth(), image.getHeight());
```
, where ```document``` is your ```PDDocument```, ```stream``` your ```PDPageContentStream``` and ```x``` and ```y``` are the positions of the image.

This would be maybe first step to try out pictures in your table cells. Then the first thing you should care about is scaling your images because you don't always want your original size picture in table cells cause it will look messy.

**Comment by dhorions** [comment]
This [Pull request](https://github.com/dhorions/boxable/pull/19) is currently being evaluated.  This contains a new class called ImageCell  that allows adding images to cells.

Will close this issue once this is released.

**Comment by dhorions** [comment]
Version (1.3)[https://github.com/dhorions/boxable/releases] is released and resolves these issues.
