### ISSUE TITLE
two headers

### ISSUE THREAD

**Issue by dluzzon** [dhorions/boxable#28]
is there a way to define two headers
Horizontal and Vertical.

and general question, there are few nice enhancments on the Pull Request.
when they are going to be merged?

**Comment by dluzzon** [comment]
just notice, no need for Vertical Header, you can just set its font to bold.

**Comment by dobluth** [comment]
Yes, that should be a valid workaround.

The intended way is `cell.setHeaderCell(true)`, which forces the cell to use the font set via `cell.setFontBold(font)` (see PR #26). But if doing so, you'd still have to set `cell.setFont(font)`, because there still is the other issue (as mentioned in #24).

As for the general question: which PR do you mean?

**Comment by dluzzon** [comment]
All those related to cell border and table border are the most important ones.

**Comment by dluzzon** [comment]
17 and 23

 

From: לוזון דני [mailto:dluzzon@gmail.com] 
Sent: Friday, March 4, 2016 9:23 AM
To: 'dhorions/boxable'
Subject: RE: [boxable] two headers (#28)

 

 

All those related to cell border and table border are the most important ones.

**Comment by Frulenzo** [comment]
@dhorions said that PRs are already in code review so maybe in few days we can expect merging or constructive feedback

**Comment by dhorions** [comment]
Version (1.3)[https://github.com/dhorions/boxable/releases] is released and resolves these issues.
