### ISSUE TITLE
getHeaderAndDataHeight gets incorrect data

### ISSUE THREAD

**Issue by daniefdz** [dhorions/boxable#29]
This method only gets a value when a header is set. And when you get a value is only the height of the header and the first cell. It should get the height of all the cells, not just the first one.

`public float getHeaderAndDataHeight() {
		return header == null ? 0 : header.getHeight() + rows.get(header == null ? 0 : 1).getHeight();
	}`

Proposed method

`	public float getHeaderAndDataHeight() {
		float height;
		for (Row<T> row : rows){
			height += row.getHeight();
		}
		return height;
	}`

**Comment by dobluth** [comment]
Several things have gone wrong with this method:

1. As you point out, it only returns a (valid) value if there is a header row.
2. I see also an issue about not having any row in the table: `IndexOutOfBoundsException`

Those are issues we have already fixed in our current (not yet released) codebase.

The most important point, however, is that this method is intended to only compute the height of the header and the first data row. This may seem weird, but the method is used to check whether the table shall start at the next page (in case the first data row does not fit on the current page).

**Comment by dhorions** [comment]
Version (1.3)[https://github.com/dhorions/boxable/releases] is released and resolves these issues.
