### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by StephenPaul** [dhorions/boxable#33]
Hey,

I want to congratulate you on a very impressive library.

Is there any possibility to add:
- a footer row
- page numbers at footer (page 1 of 5, page 2 of 5, page 3 of 5...)

**Comment by Frulenzo** [comment]
I guess, you mean a page footer by "footer row"?

This seems to be more a page layout issue and not Boxable issue, as Boxable is about rendering tables. But there is a mechanism that might come in handy: `PageProvider`.

The `PageProvider` creates new pages on the fly each time the table needs another page in the document. You can pass it as an argument in the constructor of `BaseTable`.

You could implement a `PageProvider`, which draws the footer on each new page, right after adding it:

```java
public class FooterPageProvider implements PageProvider {
  [...]
  @Override
  public PDPage createPage() {
    // create page, you can look into DefaultPageProvider for details
    PDPageContentStream stream = new PDPageContentStream(document, newPage, true, true);
    PDStreamUtils.write(stream, footerText, font, fontSize, x, y, color);
    stream.close();
  }
}
```

As the footer is not known to the table, you have to ensure it does not get overwritten by defining a proper bottom margin for the page (also an argument in the constructor of `BaseTable`).

Please be aware that you cannot write the maximum page number that way, as you do not know how many pages there will be in the document. You could, however, add the current page number using the above mechanism. Otherwise you will have to write the page numbers completely on your own, probably using the `PDStreamUtils.write()` method.

**Comment by StephenPaul** [comment]
Thanks Hrvoje,
This was helpful advice.

**Comment by dhorions** [comment]
Great to see this issue resolved.

**Comment by chxlumen** [comment]
Hi,
I just saw the DefaultPageProvider. What about adding a public getter of currentPageIndex ?
In this way one could add the page number _after_ creating the table, by iterating through the pages and calling getCurrentPageIndex().

In this way would be possible to add pagenumber and total_page_number, or?

**Comment by chxlumen** [comment]
I found an alternative solution to add footer like page#/tot-pages:

https://stackoverflow.com/questions/16581471/adding-page-numbers-using-pdfbox
