### ISSUE TITLE
Table to big starts new Page but how to handle it?

### ISSUE THREAD

**Issue by Blackbilbao** [dhorions/boxable#45]
Hi, 

I'm using your awesome boxable plugin, but i ran into a problem where i just don't know how to handle it properly.

I'm trying to add severall table on the same Page. Most of them have a fixed height due to their inputs but one table is dynamic (meaning the row count varies)

When I reach the end of the page the table (correctly) repeat its headers and contiunes to display more rows...

So back to the problem:

After the Table meantioned above there needs to be at least two more tables (if it fits) but if not how do i get the last position of the table? 

if no PageBreak happend, i currently remeber all the BaseTables. Ask each of them their height. Add them together and set the yStart correctly.

If a PageBreak happen what should i do in this situation?
 Also how do i get the "new Page"? Because currently if a PageBreak happens the logic i'm using tells the new Table defently to start at a new page. In result i have 2 half empty Pages.

Maybe someone had a similiar problem already and could help?

Thnaks in advance.

Edit: 
I should add that after those tables i force a PageBreak (due to display logic) so from there i have no problems continuing.

**Comment by Frulenzo** [comment]
> After the Table meantioned above there needs to be at least two more tables (if it fits) but if not how do i get the last position of the table? 

You can simply retrieve that as : `yPosition = table.draw();` because `draw()` method returns your last Y position after drawing a table.

> If a PageBreak happen what should i do in this situation?
> Also how do i get the "new Page"? Because currently if a PageBreak happens the logic i'm using tells the new Table defently to start at a new page. In result i have 2 half empty Pages.

Because your table is "broken" (on multiple pages) you can always retrieve your "new Page" with `table.getCurrentPage()`. 

Example: Your first table fits the first page but second table is big and doesn't fit the page. You can easily obtain `PDPage page = table2.getCurrentpage()` and start drawing on this page where your Table2 currently is (Page 2).

Hopefully that answers your question :smiley:

**Comment by Blackbilbao** [comment]
Thanks for the quick answer i will try those tips

They answer my question more than enough :)

**Comment by ardav** [comment]
```
for (Map.Entry<String, String> entry : demographicList.entrySet()) {
 				demographicSlices = demographicsData.get(entry.getKey());
 				//init table
				BaseTable tableDemographics = new BaseTable(yStart, yStartNewPage, bottomMargin, tableWidth, margin,
						doc, pageDemographics, drawLines, drawContent);
				//create table
				tableDemographics = createTableDemographics(tableDemographics, demographicSlices,
						completedCheckupCountInt, entry.getValue());
				
				yPosition = tableDemographics.draw();
				yStart = yPosition - (margin);

				if (tableDemographics.getCurrentPage() != pageDemographics) {
					streamDemographics1.close();
					pageDemographics = tableDemographics.getCurrentPage();
					streamDemographics1 = new PDPageContentStream(doc, pageDemographics, AppendMode.APPEND, false);

					streamDemographics1.beginText();
					streamDemographics1.setFont(font, 10);
					streamDemographics1.setLeading(10 * 1.2);
					streamDemographics1.newLineAtOffset(50, 710);

				}
			}
```


I am using the code above to draw multiple tables (also the rows in each table are dynamically created). The if statement at the end checks if we are at the end of the page, if so, it sets the next page and continues drawing on. ( Discussion above helped a lot, thanks!)

Here is the ss of the result  (it shows last half of one table, a whole broken table, and first half of another new table):

![screen shot 2016-04-18 at 5 51 29 pm](https://cloud.githubusercontent.com/assets/2661044/14624293/3e4ce186-058e-11e6-91cf-6b3c2652650b.png)


However the behavior I want is to start drawing the table on the next page instead of breaking it . (Of course if it is a reaaaaaaaly long table, then naturally it should break but it should still start in a new page.)

I can tell if a table is broken by calling  tableIsBroken, but that only works after the table is drawn, is it possible to check if the table definitely "will" break and move it to next page if that's the case.
 
I guess the css equivalent is  " page-break-inside: avoid; "

**Comment by dobluth** [comment]
Hi,

you can check before drawing, if the table will fit on the page:
```java
float remainingSize = yStart - bottomMargin;
float tableSize = tableDemographics.getHeaderAndDataHeight();
if (remainingSize < tableSize) {
  tableDemographics.pageBreak();
}
yPosition = tableDemographics.draw();
```

Haven't tested it, but it should point out a rough direction :)

**Comment by gstrickland** [comment]
I know this is almost a year old, but I have the same need, to force a page break if the table would not fit on the space left on the page. I am running boxable 1.5-RC. I tried the code above, but it doesn't compile, because the pageBreak() method is private in the Table class. Is there some other way?
