### ISSUE TITLE
Automatically scale cell text

### ISSUE THREAD

**Issue by giofid** [dhorions/boxable#59]
In my opinion it would be nice to automatically scale the cell text if its width is greater than cell width.

I have a cell that display the SHA256 of some data and for some hash the text width is greater than cell width.

I resolved with this code during the cell creation:

```
Cell<PDPage> cell2 = row.createCell(38f, getHash(), HorizontalAlignment.CENTER, VerticalAlignment.MIDDLE);
        cell2.setFont(font);
        float cellWidth = cell2.getWidth();
        float textWidth = font.getStringWidth(getHash())/1000*cell2.getFontSize();
        while (cellWidth < textWidth) {
            cell2.setFontSize(cell2.getFontSize()-.5f);
            cellWidth = cell2.getWidth();
            textWidth = font.getStringWidth(getHash())/1000*cell2.getFontSize();
        }
```

Do you plan on adding this feature in the future?

**Comment by dobluth** [comment]
Hi!

Scaling the font size to fit the content into a cell is a neat idea, but unfortunately only under certain circumstances. You have a SHA256 hash which always has the same length, so you can determine the necessary font size independent from your actual data (you can actually do that just knowing your cell's width). For this purpose your approach works fine.

But using it for all cells in a column or even a table would heavily disturb the layout of that table, because each cell's font size is different, depending on its content.

The usual way of handling text that is too long for a single line in a cell is to break it into multiple lines, keeping the font size. So I would in general stick with that strategy.

Markus

**Comment by 9890382866** [comment]
HI @dobluth ,

I am trying to add text in cell which i need to wrap. But its breaking directly not by space. Can you please help
